### ISSUE TITLE
Don't commit webhook URL in repo

### ISSUE THREAD

**Issue by Nishkalkashyap** [pranshupant/automate_daily_assessment#1]
Tch, tch, tch! Rookies rookies everywhere. Don't commit slack webhook URL in code repo boy :P. You were about to get a nasty message on your slack channel, had slack not disabled your webhook URL. Check your `daily_assessment.py` file

**Comment by pranshupant** [comment]
I know. That is an old URL. I have made this same mistake before though, that is why I have a separate auth.py file this time.
